# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-03 21:13
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Snippet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lastTransaction', models.DateTimeField(auto_now_add=True)),
                ('highlighted', models.TextField()),
                ('textField', models.TextField(help_text=b'Rows to modify.')),
                ('counterBefore', models.PositiveSmallIntegerField(default=0)),
                ('counterAfter', models.PositiveSmallIntegerField(default=0)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snippets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('lastTransaction',),
            },
        ),
    ]
