# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-23 14:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snippet',
            name='file',
            field=models.FileField(blank=True, upload_to=b''),
        ),
    ]
