# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-25 13:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snippet',
            name='code',
            field=models.TextField(blank=True, default=b'Default Sample of code', help_text=b'Insert Here the Text to Format'),
        ),
    ]
