# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-06 16:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='snippet',
            old_name='characterAppend',
            new_name='character',
        ),
    ]
