# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-08 13:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0002_auto_20180308_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snippet',
            name='linenos',
            field=models.BooleanField(default=False, help_text=b'Add Line Numbers in Viewing Highlighted url Link'),
        ),
    ]
