# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-08 13:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0003_auto_20180308_1448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snippet',
            name='code',
            field=models.TextField(help_text=b'Insert Here the Text to Format'),
        ),
    ]
