# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-09 10:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0004_remove_file_remark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snippet',
            name='code',
            field=models.TextField(blank=True, help_text=b'Insert Here the Text to Format'),
        ),
    ]
