# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-06 18:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0004_auto_20180306_1832'),
    ]

    operations = [
        migrations.AddField(
            model_name='snippet',
            name='datafile',
            field=models.FileField(default=False, upload_to=b''),
        ),
    ]
