# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-09 11:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0005_auto_20180309_1146'),
    ]

    operations = [
        migrations.DeleteModel(
            name='File',
        ),
        migrations.AlterField(
            model_name='snippet',
            name='file',
            field=models.FileField(help_text=b'Choose File to Upload', upload_to=b''),
        ),
    ]
