# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-06 19:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0006_auto_20180306_2008'),
    ]

    operations = [
        migrations.DeleteModel(
            name='File',
        ),
        migrations.AddField(
            model_name='snippet',
            name='file',
            field=models.FileField(default=b'', upload_to=b''),
        ),
        migrations.AddField(
            model_name='snippet',
            name='remark',
            field=models.CharField(default=b'', max_length=20),
        ),
    ]
