# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-06 19:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0007_auto_20180306_2021'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='snippet',
            name='remark',
        ),
    ]
