# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-07 19:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0008_remove_snippet_remark'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='snippet',
            name='file',
        ),
    ]
