# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-07 20:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0009_remove_snippet_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snippet',
            name='title',
            field=models.CharField(blank=True, default=b'Default Title', max_length=100),
        ),
    ]
